extern char *gl_main_menu_options[6];
extern char gl_credit_ln0[];
extern char gl_credit_ln1[];
extern char *gl_controller_options[5];
extern char *gl_display_options[2];
extern char *gl_other_options[3];
extern char *gl_cycles_frame_options[8];
extern char *gl_autosleep_options[5];
extern char *gl_help_text[10];
extern char gl_exception[];
extern char *gl_exception_types[4];
extern char *gl_menu_titles[6];
extern char *gl_keypad_menu[3];
extern char *gl_keypad_options[12];
extern char *gl_vsync_options[3];
extern unsigned long gl_autosleep_times[4];
extern char *gl_brightness_options[5];
extern char *gl_autofire_options[3];

extern void (*emuMenuMainOptions[])(void);
extern void (*emuMenuDisplayOptions[])(void);
extern void (*emuMenuControllerOptions[])(void);