extern  char *gl_main_menu_options[9] ;
extern char gl_credit_ln0[];
extern char gl_credit_ln1[];
extern char *gl_controller_options[4];
extern char *gl_autofire_options[4];
extern char *gl_display_options[4];
extern char *gl_other_options[5];
extern char *gl_autosleep_options[5];
extern char *gl_help_text[9];
extern char *gl_exception_types[4];
extern char *gl_menu_titles[6];
extern char *gl_keypad_menu[4];
extern char *gl_palettes[7];
extern u16 gl_clock_speeds[8];
extern unsigned short palettes[14];
extern char *gl_vsync_options[3];
extern char *gl_cycles_frame_options[8];
extern u32 gl_autosleep_times[4];
extern char gl_request_ext[];
extern  char *gl_brightness_options[5];
extern char *gl_keypad_options[16];